services:
  - type: web
    name: quant-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/server.py
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: "stock_market"
      - key: CORS_ORIGINS
        value: "*"
